version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:3001"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    depends_on:
      - db1
      - db2
    environment:
      - DB1_URL=postgresql://user:password@db1:5432/db1
      - DB2_URL=postgresql://user:password@db2:5432/db2
    ports:
      - "5000:5000"

  db1:
    image: postgres:13
    environment:
      POSTGRES_DB: db1
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db1_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  db2:
    image: postgres:13
    environment:
      POSTGRES_DB: db2
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db2_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

volumes:
  db1_data:
  db2_data:

